litreview/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path("", include("litreviewcore.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

litreviewcore/urls.py
from django.urls import path

from .views import (
    UserPostsView,
    home,
    index_follows,
    new_review,
    signup,
    new_ticket,
    edit_ticket,
    delete_ticket,
    edit_review,
    delete_review,
    subscribe,
    unsubscribe,
)


app_name = "core"
urlpatterns = [
    path("", home, name="home"),
    path("tickets/new/", new_ticket, name="new-ticket"),
    path("tickets/<int:ticket_id>/edit/", edit_ticket, name="edit-ticket"),
    path(
        "tickets/<int:ticket_id>/delete/", delete_ticket, name="delete-ticket"
    ),
    path("reviews/new/", new_review, name="new-review"),
    path("reviews/<int:pk>/edit/", edit_review, name="edit-review"),
    path("review/<int:pk>/delete/", delete_review, name="delete-review"),
    path("user-follows/", index_follows, name="user-follows"),
    path("user-follows/subscribe/", subscribe, name="subscribe"),
    path("user-follows/<int:pk>/unsubscribe/", unsubscribe, name="unsubscribe"),
    path("user-posts/", UserPostsView.as_view(), name="user-posts"),
    path("accounts/signup/", signup, name="signup"),
]

litreviewcore/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models


class User(AbstractUser):
    pass


class Ticket(models.Model):
    title = models.CharField(max_length=128)
    description = models.TextField(max_length=2048, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True, upload_to="book_covers/")
    time_created = models.DateTimeField(auto_now_add=True)


class Review(models.Model):
    MAX_RATING = 5
    MIN_RATING = 0

    ticket = models.ForeignKey(Ticket, blank=True, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(
        # validates that rating must be between 0 and 5
        validators=[
            MinValueValidator(MIN_RATING),
            MaxValueValidator(MAX_RATING),
        ]
    )
    headline = models.CharField(max_length=128)
    body = models.CharField(max_length=8192, blank=True)
    user = models.ForeignKey(User, blank=True, on_delete=models.CASCADE)
    time_created = models.DateTimeField(auto_now_add=True)


class UserFollows(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="following",
        verbose_name="utilisateur",
    )
    followed_user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="followed_by",
        verbose_name="utilisateur suivi",
    )

    class Meta:
        verbose_name_plural = "utilisateur suit"
        # ensures we don't get multiple UserFollows instances
        # for unique user-user_followed pairs
        constraints = [
            models.UniqueConstraint(
                "user", "followed_user", name="unique_user_followed_user"
            ),
            models.CheckConstraint(
                check=~models.Q(user__exact=models.F("followed_user")),
                name="user_not_followed_user",
            ),
        ]

litreviewcore/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import IntegerField, ModelForm

from .models import Review, Ticket, User


class UserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username"]
        help_texts = {
            "username": """
            Ce nom sera utilisé pour vous authentifier dans l'application,
            c'est celui sous lequel les autres utilisateurs vous verront.
            """
        }


class AuthenticationForm(AuthenticationForm):
    pass


class TicketForm(ModelForm):
    class Meta:
        model = Ticket
        fields = ["title", "description", "image"]
        labels = {"title": "Titre"}


class ReviewForm(ModelForm):
    rating = IntegerField(
        min_value=Review.MIN_RATING, max_value=Review.MAX_RATING
    )

    class Meta:
        model = Review
        fields = ["ticket", "headline", "rating", "body", "user"]
        labels = {"headline": "Titre", "rating": "Note", "body": "Commentaire"}

litreviewcore/views.py
from itertools import chain

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.views import generic
from django.utils.decorators import method_decorator
from django.core.paginator import Paginator
from django.http import HttpResponseBadRequest, HttpResponseForbidden
from django.forms.models import model_to_dict

from .forms import ReviewForm, UserCreationForm, TicketForm
from .models import Review, Ticket, User, UserFollows


@login_required
def home(request):
    user = request.user

    # Get all the users that THE USER follows.
    following = User.objects.filter(
        Q(followed_by__user=user) | Q(pk__exact=user.id)
    )

    # Get their reviews and tickets.
    reviews = Review.objects.filter(user__in=following).select_related(
        "user", "ticket"
    )
    tickets = (
        Ticket.objects.filter(user__in=following)
        .select_related("user")
        .prefetch_related("review_set")
    )

    # Concatenate the results.
    posts = sorted(
        chain(reviews, tickets),
        key=lambda post: post.time_created,
        reverse=True,
    )

    # Paginate the results.
    paginator = Paginator(posts, 5)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    return render(
        request,
        "litreviewcore/home.html",
        {"posts": page_obj.object_list, "page_obj": page_obj},
    )


@method_decorator(login_required, name="dispatch")
class UserPostsView(generic.ListView):
    template_name = "litreviewcore/user_posts.html"
    context_object_name = "posts"
    paginate_by = 5

    def get_queryset(self):
        """Return the user's posts."""
        current_user = self.request.user

        reviews = Review.objects.filter(user=current_user).select_related(
            "ticket"
        )
        tickets = Ticket.objects.filter(user=current_user).prefetch_related(
            "review_set"
        )
        posts = sorted(
            chain(reviews, tickets),
            key=lambda post: post.time_created,
            reverse=True,
        )

        return posts


@login_required
def new_ticket(request):
    if request.method == "POST":
        form = TicketForm(request.POST, request.FILES)

        if form.is_valid():
            ticket = form.cleaned_data
            ticket["user"] = request.user
            Ticket(**ticket).save()
            return redirect("core:user-posts")
    else:
        form = TicketForm()

    return render(request, "litreviewcore/new_ticket.html", {"form": form})


@login_required
def edit_ticket(request, ticket_id):
    ticket = get_object_or_404(Ticket, pk=ticket_id)

    if ticket.user != request.user:
        return HttpResponseForbidden()

    if request.method == "POST":
        form = TicketForm(request.POST, request.FILES)

        if form.is_valid():
            ticket_new_data = form.cleaned_data
            ticket_new_data["user"] = request.user
            ticket.title = ticket_new_data.get("title")
            ticket.description = ticket_new_data.get("description")

            new_image = ticket_new_data.get("image")
            if new_image:
                ticket.image = new_image

            ticket.save()
            return redirect("core:user-posts")
    else:
        data = model_to_dict(ticket, fields=TicketForm.Meta.fields)
        form = TicketForm(data)

    return render(
        request,
        "litreviewcore/edit_ticket.html",
        {"ticket": ticket, "form": form},
    )


@login_required
def delete_ticket(request, ticket_id):
    ticket = get_object_or_404(Ticket, pk=ticket_id)

    if ticket.user != request.user:
        return HttpResponseForbidden()

    if request.method == "POST":
        ticket.delete()
        return redirect("core:user-posts")

    return render(
        request, "litreviewcore/delete_ticket.html", {"ticket": ticket}
    )


@login_required
def new_review(request):
    ticket_id = request.GET.get("ticket")
    ticket = Ticket.objects.filter(pk=ticket_id).first()
    ticket_form = (
        TicketForm(request.POST, request.FILES)
        if request.method == "POST"
        else TicketForm()
    )

    if request.method == "POST":
        review_form = ReviewForm(request.POST)

        if review_form.is_valid():
            review = review_form.cleaned_data

            if not ticket and ticket_form.is_valid():
                ticket = ticket_form.cleaned_data
                ticket["user"] = request.user
                ticket = Ticket(**ticket)
                ticket.save()

            review["ticket"] = ticket
            review["user"] = request.user
            Review(**review).save()
            return redirect("core:home")
    else:
        review_form = ReviewForm()

    user_is_author = (
        True if (not ticket or ticket.user == request.user) else False
    )

    return render(
        request,
        "litreviewcore/new_review.html",
        {
            "review_form": review_form,
            "ticket": ticket,
            "ticket_form": ticket_form,
            "user_is_author": user_is_author,
        },
    )


@login_required
def edit_review(request, pk):
    review = get_object_or_404(Review, pk=pk)

    if review.user != request.user:
        return HttpResponseForbidden()

    form = ReviewForm(
        request.POST or None,
        initial=model_to_dict(review),
    )
    if request.method == "POST" and form.is_valid():
        review.headline = form.cleaned_data["headline"]
        review.body = form.cleaned_data["body"]
        review.rating = form.cleaned_data["rating"]
        review.save()

        return redirect("core:user-posts")

    return render(
        request,
        "litreviewcore/edit_review.html",
        {"review": review, "form": form},
    )


@login_required
def delete_review(request, pk):
    review = get_object_or_404(Review, pk=pk)

    if review.user != request.user:
        return HttpResponseForbidden()

    if request.method == "POST":
        review.delete()
        return redirect("core:user-posts")

    return render(
        request, "litreviewcore/delete_review.html", {"review": review}
    )


@login_required
def index_follows(request):
    user = request.user

    followings = UserFollows.objects.filter(user=user).select_related(
        "followed_user"
    )
    followers = UserFollows.objects.filter(followed_user=user).select_related(
        "user"
    )

    return render(
        request,
        "litreviewcore/user_follows.html",
        {"followings": followings, "followers": followers},
    )


@login_required
def subscribe(request):
    if request.method != "POST":
        return HttpResponseBadRequest()

    followed_user_username = request.POST.get("username")
    followed_user = get_object_or_404(User, username=followed_user_username)
    user_follows = UserFollows(user=request.user, followed_user=followed_user)
    user_follows.save()
    return redirect("core:user-follows")


@login_required
def unsubscribe(request, pk):
    user_follows = get_object_or_404(UserFollows, pk=pk)

    if user_follows.user == request.user:
        user_follows.delete()
    else:
        return HttpResponseForbidden()

    return redirect("core:user-follows")


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            raw_password = form.cleaned_data["password1"]
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect("core:home")
    else:
        form = UserCreationForm()

    return render(request, "registration/signup.html", {"form": form})

litreviewcore/templates/litreviewcore/delete_review.html
{% extends "base.html" %}

{% block content %}

{% load post_extras %}

{% show_review review user False True %}

{% endblock%}

litreviewcore/templates/litreviewcore/edit_review.html
{% extends 'base.html' %}

{% block content %}

<div class="container my-5">
    <div class="row justify-content-center my-5">
        <div class="col-10 col-lg-8">
            <h2 class="h4 text-center mb-4">Modifier votre critique</h2>
        </div>
        <div class="col-10 col-lg-8">
            <form action="{% url "core:edit-review" review.id %}" method="POST" class="row">
                {% csrf_token %}
                <div class="col-12 mb-3">
                    <label for="{{ form.headline.id_for_label }}" class="form-label">{{ form.headline.label }}</label>
                    <input
                        type="text"
                        maxlength="{{ form.headline.field.max_length }}"
                        class="form-control {% if form.headline.errors %} is-invalid {% endif %}"
                        id="{{ form.headline.id_for_label }}"
                        name="{{ form.headline.html_name }}"
                        placeholder="{{ form.headline.label }}"
                        aria-label="{{ form.headline.label }}"
                        aria-describedby="{{ form.headline.id_for_label }}_errors"
                        {% if form.headline.value %} value="{{ form.headline.value }}" {% endif %}
                        required
                    />
                    <div id="{{ form.headline.id_for_label }}_errors" class="invalid-feedback">

                        {% for error in form.headline.errors %}

                            <p>{{ error }}</p>

                        {% endfor %}

                    </div>
                </div>
                <div class="col-12-mb-3">
                    <label for="{{ form.rating.id_for_label }}" class="form-label">{{ form.rating.label }}</label>
                    <input
                        class="form-range"
                        type="range"
                        min="{{ form.rating.field.min_value }}"
                        max="{{ form.rating.field.max_value }}"
                        step="1"
                        id="{{ form.rating.id_for_label }}"
                        name="{{ form.rating.html_name }}"
                        aria-label="{{ form.rating.label }}"
                        {% if form.rating.value %} value="{{ form.rating.value }}" {% endif %}
                    />
                </div>
                <div class="col-12 mb-3">
                    <label for="{{ form.body.id_for_label }}" class="form-label">{{ form.body.label }}</label>
                    <textarea
                        class="form-control {% if form.body.errors %} is-invalid {% endif %}"
                        id="{{ form.body.id_for_label }}"
                        name="{{ form.body.html_name }}"
                        aria-label="{{ form.body.label }}"
                        aria-describedby="{{ form.body.id_for_label }}_errors"
                    >{% if form.body.value %}{{ form.body.value }}{% endif %}</textarea>
                    <div id="{{ form.body.id_for_label }}_errors" class="invalid-feedback">

                        {% for error in form.body.errors %}

                            <p>{{ error }}</p>

                        {% endfor %}

                    </div>
                </div>
                <div class="col-12 mb-3 text-center text-sm-end">
                    <button type="submit" class="btn btn-primary">Envoyer</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

litreviewcore/templates/litreviewcore/edit_ticket.html
{% extends "base.html" %}

{% block content %}

<div class="container my-5">
    <div class="row justify-content-center my-4">
        <div class="col-10 col-lg-8">
            <h2 class="h4 text-center mb-4">Modifier votre ticket</h2>
        </div>
        <div class="col-10 col-lg-8">
            <form action="{% url 'core:edit-ticket' ticket.id %}" method="POST" enctype="multipart/form-data" class="row">
                {% csrf_token %}
                <div class="col-12 mb-3">
                    <label for="{{ form.title.id_for_label }}">{{ form.title.label }}</label>
                    <input
                      type="text"
                      class="form-control"
                      id="{{ form.title.id_for_label }}"
                      name="{{ form.title.html_name }}"
                      placeholder="{{ form.title.label }}"
                      aria-label="{{ form.title.label }}"
                      {% if form.title.value %} value="{{ form.title.value }}" {% endif %}
                      required
                    />
                </div>
                <div class="col-12 mb-3">
                    <label for="{{ form.description.id_for_label }}" class="form-label">{{ form.description.label }}</label>
                    <textarea
                      class="form-control"
                      id="{{ form.description.id_for_label }}"
                      name="{{ form.description.html_name }}"
                      placeholder="{{ form.description.label }}"
                      aria-label="{{ form.description.label }}"
                    >{% if form.description.value %}{{ form.description.value }}{% endif %}</textarea>
                </div>

                {% if ticket.image %}

                    <div class="col-12 mb-3">
                        <img src="{{ ticket.image.url}}" alt="Couverture du livre" width="150px">
                    </div>

                {% endif %}

                <div class="col-12 mb-3">
                    <label for="{{ form.image.id_for_label }}"></label>
                    <input 
                      type="file"
                      name="{{ form.image.html_name }}"
                      id="{{ form.image.id_for_label }}"
                      accept="image/png, image/jpeg"
                    />
                </div>
                <div class="col-12 mb-3 text-center text-sm-end">
                    <button type="submit" class="btn btn-primary">Envoyer</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock%}

litreviewcore/templates/litreviewcore/home.html
{% extends "base.html" %}

{% block content %}

{% load post_extras %}

<div class="container my-5">

    <div class="row justify-content-center my-4">
        <div class="col-10 col-lg-8">
            <div class="row gy-2">
                <div class="col-lg-6 text-center">
                    <a href="{% url 'core:new-ticket' %}" class="btn btn-outline-dark d-block">Demander une critique</a>
                </div>
                <div class="col-lg-6 text-center">
                    <a href="{% url 'core:new-review' %}" class="btn btn-outline-dark d-block">Créer une critique</a>
                </div>
            </div>
        </div>
    </div>

    {% for post in posts %}

        {% if post|is_review %}

            {% show_review post user %}

        {% else %}

            {% show_ticket post user %}

        {% endif %}

    {% endfor %}

    <div class="row pagination">
        <div class="col-12 text-center">
            <span class="step-links">

                {% if page_obj.has_previous %}
                
                    <span class="prev">
                        <a href="?page=1">&laquo; première</a>
                        <a href="?page={{ page_obj.previous_page_number }}">page précédente</a>
                        &nbsp;&verbar;&nbsp;
                    </span>

                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} sur {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}

                    <span class="next">
                        &nbsp;&verbar;&nbsp;
                        <a href="?page={{ page_obj.next_page_number }}">page suivante</a>
                    </span>

                    <a href="?page={{ page_obj.paginator.num_pages }}">dernière &raquo;</a>

                {% endif %}

            </span>
        </div>
    </div>

</div>

{% endblock %}

litreviewcore/templates/litreviewcore/new_ticket.html
{% extends "base.html" %}

{% block content %}

<div class="container my-5">
    <div class="row justify-content-center my-4">
        <div class="col-10 col-lg-8">
            <form action="{% url 'core:new-ticket' %}" method="POST" enctype="multipart/form-data" class="row">
                {% csrf_token %}
                <div class="col-12 mb-3">
                    <label for="{{ form.title.id_for_label }}">{{ form.title.label }}</label>
                    <input
                      type="text"
                      class="form-control"
                      id="{{ form.title.id_for_label }}"
                      name="{{ form.title.html_name }}"
                      placeholder="{{ form.title.label }}"
                      aria-label="{{ form.title.label }}"
                      {% if form.title.value %} value="{{ form.title.value }}" {% endif %}
                      required
                    />
                </div>
                <div class="col-12 mb-3">
                    <label for="{{ form.description.id_for_label }}" class="form-label">{{ form.description.label }}</label>
                    <textarea
                      class="form-control"
                      id="{{ form.description.id_for_label }}"
                      name="{{ form.description.html_name }}"
                      placeholder="{{ form.description.label }}"
                      aria-label="{{ form.description.label }}"
                    ></textarea>
                </div>
                <div class="col-12 mb-3">
                    <label for="{{ form.image.id_for_label }}"></label>
                    <input 
                      type="file"
                      name="{{ form.image.html_name }}"
                      id="{{ form.image.id_for_label }}"
                      accept="image/png, image/jpeg">
                </div>
                <div class="col-12 mb-3 text-center text-sm-end">
                    <button type="submit" class="btn btn-primary">Envoyer</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

litreviewcore/templates/litreviewcore/review.html
<div class="row justify-content-center my-3">
    <div class="col-10 col-lg-8 border rounded pt-3">
        <div class="row">
            <p class="col-6">
                <span class="badge {% if user_is_author %} bg-info {% else %} bg-primary {% endif %}">

                    {% if user_is_author %}

                        Vous

                    {% else %}

                        {{ review.user }}

                    {% endif %}

                </span> {% if user_is_author %} avez {% else %} a {% endif %} publié une critique
            </p>
            <p class="col-6 text-end text-secondary fs-6 fw-light fst-italic">
                <span>{{ review.time_created }}</span>
            </p>
        </div>

        <div class="row">
            <h2 class="h4">
                {% load post_extras %}
                {{ review.headline }} - {% get_stars review.rating %}
            </h2>
        </div>

        <div class="row">
            <p>{{ review.body }}</p>
        </div>

        {% if is_user_posts %}

             <div class="row justify-content-end">
                 <div class="col--md-6 text-md-end text-center">
                     <a href="{% url "core:edit-review" review.id %}" class="btn btn-outline-dark my-4 mx-2">Modifier</a>
                     <a href="{% url "core:delete-review" review.id %}" class="btn btn-outline-dark my-4 mx-2">Supprimer</a>
                 </div>
             </div>

         {% endif %}

        {% comment %}
            This if branch does not really matter as per now every review has to have a ticket.
            Some dummy data that was created at the beginning of the project does not enforce this principle (as the model does not),
            so it does not harm to leave it there.
        {% endcomment %}
        {% if review.ticket %}

            <div class="row p-3">
                <div class="container">
                    <div class="row bg-light py-2 rounded">
                        <div class="col-12">
                           <p>
                                <span class="h5">Ticket</span>
                                <span class="badge bg-secondary">

                                    {% if review.ticket.user == user %}

                                        Vous

                                    {% else %}

                                        {{ review.ticket.user }}

                                    {% endif %}
                                    
                                </span>
                            </p>
                        </div>
                        <div class="col-12">
                            <h3 class="h6">{{ review.ticket.title }}</h3>
                        </div>

                        {% if review.ticket.description %}

                            <div class="col-12">
                                <p>{{ review.ticket.description }}</p>
                            </div>

                        {% endif %}

                        {% if review.ticket.image %}

                            <div class="col-12">
                                <img src="{{ review.ticket.image.url }}" alt="Couverture du livre" width="150px">
                            </div>

                        {% endif %}

                    </div>
                </div>
            </div>

        {% endif %}

        
        {% if is_delete_post %}

            <div class="col-12">
                <form action="{% url 'core:delete-review' review.id %}" method="POST" class="text-center text-md-end">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger my-2">Supprimer</button>
                </form>
            </div>

        {% endif %}

    </div>
</div>

litreviewcore/templates/litreviewcore/ticket.html
<div class="row justify-content-center my-3">
    <div class="col-10 col-lg-8 border rounded pt-3">
        <div class="row">
            <p class="col-6">
                <span class="badge {% if user_is_author %} bg-info {% else %} bg-primary {% endif %}">

                    {% if user_is_author %}

                        Vous

                    {% else %}

                        {{ ticket.user }}

                    {% endif %}

                </span> {% if user_is_author %} avez {% else %} a {% endif %} demandé une critique
            </p>
            <p class="col-6 text-end text-secondary fs-6 fw-light fst-italic">
                <span>{{ ticket.time_created }}</span>
            </p>
        </div>

        <div class="row">
            <h2 class="h4">{{ ticket.title }}</h2>
        </div>

         {% if ticket.description %}

             <div class="row">
                 <p>{{ ticket.description }}</p>
             </div>

         {% endif %}

        <div class="row justify-content-end">

            {% if is_delete_post %}

                <div class="col-12 col-sm-4">
                    <form action="{% url 'core:delete-ticket' ticket.id %}" method="POST" class="text-center text-md-end">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger my-2">Supprimer</button>
                    </form>
                </div>

            {% elif not is_user_posts %}

                <div class="col-4">

                    {% if ticket.review_set.count == 0 %}

                        <a href="{% url 'core:new-review' %}?ticket={{ ticket.id }}" class="btn btn-outline-dark my-2">Créer une critique</a>

                    {% else %}

                        <a class="btn btn-outline-dark my-2 disabled" aria-disabled="true">Créer une critique</a>

                    {% endif %}

                </div>

            {% endif %}

        </div>

         {% if ticket.image %}

             <div class="row">
                 <div class="col-12 mb-4">
                     <img src="{{ ticket.image.url }}" alt="Couverture du livre" width="150px">
                 </div>
             </div>

         {% endif %}

         {% if is_user_posts %}

             <div class="row justify-content-end">
                 <div class="col--md-6 text-md-end text-center">
                     <a href="{% url "core:edit-ticket" ticket.id %}" class="btn btn-outline-dark my-4 mx-2">Modifier</a>
                     <a href="{% url "core:delete-ticket" ticket.id %}" class="btn btn-outline-dark my-4 mx-2">Supprimer</a>
                 </div>
             </div>

         {% endif %}

    </div>
</div>

litreviewcore/templates/litreviewcore/user_follows.html
{% extends "base.html" %}

{% block content %}

<div class="container my-5">
    <div class="row justify-content-center my-4">
        <div class="col-10 col-lg-8">
            <h2 class="h4 my-4 text-center">Suivre d'autres utilisateurs</h2>
                <form method="POST" action="{% url 'core:subscribe' %}" class="row">
                    {% csrf_token %}
                    <div class="col-10 mb-3 py-2">
                        <input class="w-100" type="text" name="username" placeholder="Nom d'utilisateur">
                    </div>
                    <div class="col-2 mb-3 py-1">
                        <button class="btn btn-primary" type="submit">Envoyer</button>
                    </div>
                </form>
        </div>
        <div class="col-10 col-lg-8">
            <h2 class="h4 my-4 text-center">Abonnements</h2>
                <table class="table table-striped">

                    {% if followings|length %}

                        {% for following in followings %}

                            <tr>
                                <td class="w-75 align-middle">{{ following.followed_user }}</td>
                                <td>
                                    <form method="POST" action="{% url 'core:unsubscribe' following.id %}">
                                        {% csrf_token %}
                                        <button class="btn btn-danger" type="submit">Se désabonner</button>
                                    </form>
                                </td>
                            </tr>

                        {% endfor %}

                    {% endif %}

                </table>
        </div>
        <div class="col-10 col-lg-8">
            <h2 class="h4 my-4 text-center">Abonnés</h2>
                <table class="table table-striped">

                    {% if followers|length %}

                        {% for follower in followers %}

                            <tr>
                                <td class="w-75 align-middle">{{ follower.user }}</td>
                            </tr>

                        {% endfor %}

                    {% endif %}

                </table>
        </div>
    </div>
</div>

{% endblock %}